# ssh peterchin8.bu.edu
# source ~/env/bin/activate
# cd lisp/dl-hyperbolic-random-graphs/path_approximation/src/
random_seed: 7
graph:
  source: "gis-f2e"
  name: "surat" # "dongguan"
  diameter: 7.5
  file_path: "../data/{name}.{source}"
  download_type: "drive"
  coord_path: "../data/{name}.co"
  plot_path: "../plots/{name}"
collab_filtering:
  "device": "cuda:0"
  "embedding_dim": 128
  "batch_size": 0
  "epochs": 100
  "lr": 0.03
  "loss_func": "custom" # "mre"
  "optimizer": "adam"
  "sample_ratio": 0.1
  "test_sample_ratio": 0.9
  "init_embedding": "none" # "coord"

  "measure": "inv-dot" # "norm" "spherical" "poincare" "hyperboloid" "lat-long" "inv-dot"
  "norm": 6
run_routing: False

grarep:
  "embedding_dim": 128
  "iterations": 10
  "order": 100
node2vec:
  "embedding_dim": 128
  "walk_length": 80
  "window_size": 10
  "p": 1
  "q": 1
  "num_walks": 10
  "epochs": 100
  "batch_size": 256
  "lr": 0.01


plot:
  plot_nx_graph: False
val_size: 0.2 # val/train = 20% / 80%, for training
log_path: "../output/logs"
force_recreate_train_and_val_sets: False
force_recreate_test_set: False
write_train_val_sets: True
write_test_set: True
parse_tuning_param_by: ->  ## helpful to create a list of configs
routing_num_samples: 25000
# df = pd.read_csv("routes.csv", names=["source", "target", "numVisited", "pathLength"])