##### Config for generating datasets
## `key: value`, or `key: {key':value}`
## For tuning parameters, set `value` as a list (e.g.,  if we set `sample_method: ['random', 'high_degree', 'high_and_low_degree']`, we will generate 3 different configs)
random_seed: 42
graph:
  source: "osmnx" # "edgelist", "gr"
  name: "cambridge ma" # USA-road-t.NY
  file_path: "../data/{name}.{source}"
  download_type: "walk"
  coord_path: "../data/{name}.co"
  plot_path: "../plots/{name}"
coord2vec:
  "device": cuda
  "embedding_dim": 2
  "batch_size": 16384
  "epochs": 100
  "lr": 0.03
  "sample_ratio": 0.3
collab_filtering:
  "device": cuda
  "embedding_dim": 25
  "batch_size": 1024
  "epochs": 25
  "lr": 0.0003
  "sample_ratio": 0.3
plot:
  plot_nx_graph: False
val_size: 0.2 # val/train = 20% / 80%, for training
log_path: "../output/logs"
force_recreate_train_and_val_sets: False
force_recreate_test_set: False
write_train_val_sets: True
write_test_set: True
parse_tuning_param_by: ->  ## helpful to create a list of configs
routing_num_samples: 1000