##### Config for generating datasets
## `key: value`, or `key: {key':value}`
## For tuning parameters, set `value` as a list (e.g.,  if we set `sample_method: ['random', 'high_degree', 'high_and_low_degree']`, we will generate 3 different configs)
random_seed: 42
data:
  file_name: small_test # "small_test" is a small network file for testing. Other data are in "/data" folder, should start off with a small dataset.
  input_path: "../data/{file_name}.edgelist"
  embedding_output_path: "../output/embedding/{file_name}_embed-epochs{epochs}-lr{lr}.pkl"
  landmark_distance_output_path: "../output/landmarks_distance/{file_name}_dist.pkl"
  final_train_val_sets_path: "../output/datasets/{file_name}_train_val_sets-landmark_ratio-{sample_ratio_for_training}-sample_method-{sample_method}-val_size-{val_size}.pkl"
  final_test_set_path: "../output/datasets/{file_name}_test_set-landmark_ratio-{sample_ratio_for_testing}-sample_method-{sample_method}.pkl"
node2vec:
  "device": cuda
  "embedding_dim": 128
  "walk_length": 5
  "window_size": 5
  "p": 0.2
  "q": 4
  "num_walks": 25
  "epochs": 100
  "batch_size": 128
  "lr": 0.01
landmark:
  sample_method: high_degree #[ high_degree, random ]  # valid methods: ['betweenness_centrality', 'closeness_centrality','random','high_degree','medium_degree']
  sample_ratio_for_training: 0.5 #[ 0.2,0.3,0.4,0.5,0.6,0.7 ]
  sample_ratio_for_testing: 0.7 ## use 0.7  (70%) nodes as landmarks, then get all distance pairs from these landmarks to create labels.
plot:
  plot_nx_graph: False
val_size: 0.2 # val/train = 20% / 80%, for training
log_path: "../output/logs"
force_recreate_train_and_val_sets: True
force_recreate_test_set: True
write_train_val_sets: True
write_test_set: True
parse_tuning_param_by: ->  ## helpful to create a list of configs