# ssh peterchin8.bu.edu
# source ~/env/bin/activate
# cd lisp/dl-hyperbolic-random-graphs/path_approximation/src/
random_seed: 7
graph:
  source: "gis-f2e"
  name: "surat"   # "dongguan" "surat" 
  diameter: 7.0 # 7.0 , 9.0
  max_weight: 7294.463374338059
  file_path: "../data/{name}.{source}"
  download_type: "drive"
  coord_path: "../data/{name}.co"
  plot_path: "../plots/{name}"
collab_filtering:
  "device": "cuda:1"
  "embedding_dim": 52 # 52, 167
  "epochs": 20
  "lr": 0.0003
  "loss_func": "mse"
  "optimizer": "adam"
  "sample_ratio": 1.0
  "test_sample_ratio": 0.0

  "batch_size": 2591 # 2591, 8315
  "init_embedding": "node2vec" # "coord" "node2vec" "grarep" "none"
  "measure": "inv-dot" # "norm" "spherical" "poincare" "hyperboloid" "lat-long" "inv-dot"
  "norm": 2
run_routing: False
run_dist_routing: False
plot_routes: True
test_results: False

grarep:
  "embedding_dim": 52
  "iterations": 10
  "order": 100
node2vec:
  "embedding_dim": 52
  "walk_length": 80
  "window_size": 10
  "p": 1
  "q": 1
  "num_walks": 10
  "epochs": 100
  "batch_size": 256
  "lr": 0.01


plot:
  plot_nx_graph: False
val_size: 0.2 # val/train = 20% / 80%, for training
log_path: "../output/logs"
force_recreate_train_and_val_sets: False
force_recreate_test_set: False
write_train_val_sets: True
write_test_set: True
parse_tuning_param_by: ->  ## helpful to create a list of configs
routing_num_samples: 25000
